<div class="header row">
		<ul class="service-bar col-xs-5 col-xs-offset-7" id="game1-service-bar">
			<li class="service-cell" >
				<a class="service-link" href="home/" data-action="Home">首页</a>
				</li>
			<li class="service-cell">
				<a href="/user/login/" onclick="return Login.open()">登录</a>
				或者
				<a href="/user/register/">注册账号</a>
			</li>
			<li class="service-cell">
				<a class="service-link" href="https://www.battlenet.com.cn/shop/" data-action="Shop">充值</a>
			</li>
			<li class="service-cell">
			<a class="service-link" href="https://www.battlenet.com.cn/account/management/" data-action="Account">客服</a>
			</li>
		</ul>
</div>



<div id="logo" class="logo row">
	<div class="logo-left col-xs-6">
		<div>
 			<img  src="/img/game1/game1-logo.jpg" alt=""/>
			
		</div>
	
	</div>
 
	<div class="col-xs-offset-2 col-xs-4 logo-right">
		    <div class="input-group">
		      <input type="text" class="form-control" id="form-control">

		      <span class="input-group-btn">
		        <button class="btn btn-default" id="btn-default" type="button">Go!</button>
		      </span>
		    </div>
	</div>
	
</div><!-- /.row -->

<div class="game1main row">		
 	<div id="menu" class=" col-xs-8">
	<ul class="menu" >
		<li class="menu-home" itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement">
			<a class="menu-active" itemprop="url" href="/wow/zh/">
			<span itemprop="name">主页</span>
			</a>
		</li>
		<li class="menu-game" itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement">
			<a itemprop="url" href="/wow/zh/game/">
			<span itemprop="name">游戏指南</span>
			</a>
		</li>
		<li class="menu-community" itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement">
			<a itemprop="url" href="/wow/zh/community/">
			<span itemprop="name">社区</span>
			</a>
		</li>
		<li class="menu-media" itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement">
			<a itemprop="url" href="/wow/zh/media/">
			<span itemprop="name">媒体</span>
			</a>
		</li>
		<li class="menu-forums" itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement">
			<a itemprop="url" href="/wow/zh/forum/">
			<span itemprop="name">论坛</span>
			</a>
		</li>
		<li class="menu-services" itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement">
			<a itemprop="url" href="/wow/zh/shop/">
			<span itemprop="name">服务</span>
			</a>
		</li>
	</ul>	
 	</div>
 	
	<div class="user-plate col-xs-4">
		<a class="card-character plate-logged-out" href="?login" onclick="return Login.open('https://www.battlenet.com.cn/login/login.frag');">
			<span class="card-portrait"></span>
			<span class="wow-login-key"></span>
			<span class="login-msg">
				<strong>登录</strong>
				您的通行证以发表评论并进行个性化设置。
			</span>
		</a>
	</div>
	
</div>
 
<div class="game1-img-news row">
<!-- 
	<div class="img-news-left col-xs-8" id="img-news-left">
 			<a id="game1-001" class="bnet-offer-image" href="http://www.wowchina.com/activities/mcd/" target="_blank" >
			<img width="640" height="300" src="/img/game1/cont-left-1.jpg" alt=""/>
			</a>
	
	</div>
 -->	
	<div class="img-news-left col-xs-8" id="img-news-left">

	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
	  <!-- Indicators -->
	  <ol class="carousel-indicators">
	    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
	    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
	    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
	  </ol>
	
	  <!-- Wrapper for slides -->
	  <div class="carousel-inner" role="listbox">

	  	<div class="item active">
	      <img src="/img/game1/cont-left-1.jpg" alt="img1">
	      <div class="carousel-caption">

	      </div>
	    </div>

	    <div class="item">
	      <img src="/img/game1/cont-left-2.jpg" alt="img2">
	      <div class="carousel-caption">
	      
	      </div>
	    </div>

	    <div class="item">
	      <img src="/img/game1/cont-left-3.jpg" alt="img3">
	      <div class="carousel-caption">
	      
	      </div>
	    </div>

	  </div>
	
	  <!-- Controls -->
	  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
	    <span class="glyphicon glyphicon-chevron-left"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
	    <span class="glyphicon glyphicon-chevron-right"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div>
	
	</div>
	
	<div class="img-news-right col-xs-4" id="img-news-right">
			<a id="game1-002" class="bnet-offer-image" href="http://www.wowchina.com/activities/mcd/" target="_blank" >
			<img width="300" height="250" src="/img/game1/cont-right-1.jpg" alt=""/>
			</a>
	</div>
	
</div>

<div class="game1-article-news row">

	<div class="article-news-left col-xs-8" id="article-news-left ">
 
<!-- 		<div id="blog-articles" class="blog-articles" itemscope="itemscope" itemtype="http://schema.org/Blog">

		<div class="article-wrapper">
			<a href="/wow/zh/blog/14266432/%E3%80%8A%E9%92%A2%E9%93%81%E9%83%A8%E8%90%BD%E5%85%A5%E4%BE%B5%E3%80%8B%E4%B8%93%E9%A2%98%E7%BD%91%E7%AB%99%E4%B8%8A%E7%BA%BF-2014%E5%B9%B410%E6%9C%8814%E6%97%A5" itemprop="url">
			<div class="article-image" style="background-image:url(/img/game1/article-left-1.jpg)">
 				<div class="article-image-frame"></div>
				</div>
			<div class="article-content" itemprop="blogPost" itemscope="itemscope" itemtype="http://schema.org/BlogPosting">
				<h2 class="header-2">
					<span class="article-title" itemprop="headline"> 《钢铁部落入侵》专题网站上线 </span>
				</h2>
				<span class="clear"></span>
				<div class="article-summary" itemprop="description">
				资料片《熊猫人之谜》最后一个内容版本《钢铁部落入侵》将在10月16日上线。而我们的
					<a href="http://www.wowchina.com/wod/new" target="_blank">《钢铁部落入侵》版本专题网站</a>
				也已上线，在专题网站中我们将对这一补丁中的一些重要改动及新内容进行介绍。
				</div>
				<span class="clear"></span>
				<meta itemprop="datePublished" content="2014-10-14T11:23:12+08"/>
				<meta itemprop="dateModified" content="2014-10-14T11:23:49+08"/>
				<meta itemprop="inLanguage" content="zh-CN"/>
				<meta itemprop="interactionCount" content="UserComments:123"/>
				<meta itemprop="thumbnailUrl" content="//cms-origin-cn.battle.net/cms/connect_thumbnail/td/TDHRTD5DIRKI1411892913227.jpg"/>
			</div>
			</a>
			<div class="article-meta">
				<span class="publish-date" title="2014年10月14日 11:23 CST"> 22 小时前 </span>
				<a class="comments-link" href="/wow/zh/blog/14266432/%E3%80%8A%E9%92%A2%E9%93%81%E9%83%A8%E8%90%BD%E5%85%A5%E4%BE%B5%E3%80%8B%E4%B8%93%E9%A2%98%E7%BD%91%E7%AB%99%E4%B8%8A%E7%BA%BF-2014%E5%B9%B410%E6%9C%8814%E6%97%A5#comments">123</a>
			</div>
			<span class="clear"></span>
		</div> 	
 --> 	
		<div id="blog-articles" class="blog-articles" >
	
			<div class="article-wrapper">

				<div class="article-image" >
 				<img width="190" height="96" src="/img/game1/article-left-1.jpg" alt=""/>
				</div>
		 
				<div class="article-content" >
					
						<h2 class="header-2">
							<span class="article-title" > 《钢铁部落入侵》专题网站上线 </span>
						</h2>
						<span class="clear"></span>

 					<div class="article-summary" >
					资料片《熊猫人之谜》最后一个内容版本《钢铁部落入侵》将在10月16日上线。而我们的
						<a href="http://www.wowchina.com/wod/new" target="_blank">《钢铁部落入侵》版本专题网站</a>
					也已上线，在专题网站中我们将对这一补丁中的一些重要改动及新内容进行介绍。
					</div>						
					<span class="clear"></span>
					
					<div class="article-meta">
						<span class="publish-date" title="2014年10月14日 11:23 CST"> 22 小时前 </span>
						<a class="comments-link" href="/wow/zh/blog/14266432/left-1">123</a>
					</div>
					<span class="clear"></span>
					
				</div>
			</div>
			
 		<div class="article-wrapper">

				<div class="article-image" >
 					<img width="190" height="96" src="/img/game1/article-left-2.jpg" alt=""/>
				</div>
		 
				<div class="article-content" >
					
	 				<div class="aaaaa">
						<h2 class="header-2">
							<span class="article-title" > 《钢铁部落入侵》专题网站上线 </span>
						</h2>
						<span class="clear"></span>
					</div>

 					<div class="article-summary" >
					资料片《熊猫人之谜》最后一个内容版本《钢铁部落入侵》将在10月16日上线。而我们的
						<a href="http://www.wowchina.com/wod/new" target="_blank">《钢铁部落入侵》版本专题网站</a>
					也已上线，在专题网站中我们将对这一补丁中的一些重要改动及新内容进行介绍。
					</div>						
					<span class="clear"></span>
					
					<div class="article-meta">
						<span class="publish-date" title="2014年10月14日 11:23 CST"> 22 小时前 </span>
						<a class="comments-link" href="/wow/zh/blog/14266432/left-2">123</a>
					</div>
					<span class="clear"></span>
					
				</div>
			</div>

 		<div class="article-wrapper">

				<div class="article-image" >
 					<img width="190" height="96" src="/img/game1/article-left-3.jpg" alt=""/>
				</div>
		 
				<div class="article-content" >
					
	 				<div class="aaaaa">
						<h2 class="header-2">
							<span class="article-title" > 《钢铁部落入侵》专题网站上线 </span>
						</h2>
						<span class="clear"></span>
					</div>

 					<div class="article-summary" >
					资料片《熊猫人之谜》最后一个内容版本《钢铁部落入侵》将在10月16日上线。而我们的
						<a href="http://www.wowchina.com/wod/new" target="_blank">《钢铁部落入侵》版本专题网站</a>
					也已上线，在专题网站中我们将对这一补丁中的一些重要改动及新内容进行介绍。
					</div>						
					<span class="clear"></span>
					
					<div class="article-meta">
						<span class="publish-date" title="2014年10月14日 11:23 CST"> 22 小时前 </span>
						<a class="comments-link" href="/wow/zh/blog/14266432/left-3">123</a>
					</div>
					<span class="clear"></span>
					
				</div>
			</div>
			
			
		</div> 	
		
	</div>
	
	<div class="article-news-right col-xs-4" id="article-news-right ">
	<a target="_blank" class="sidebar-link" href="https://www.battlenet.com.cn/account/creation/wow/signup/index.xml" style="background-image:url('/img/game1/article-right-1.jpg');"></a>

	<a target="_blank" class="sidebar-link" href="https://www.battlenet.com.cn/account/creation/wow/signup/index.xml" style="background-image:url('/img/game1/article-right-2.jpg');"></a>
	
	<a target="_blank" class="sidebar-link" href="https://www.battlenet.com.cn/account/creation/wow/signup/index.xml" style="background-image:url('/img/game1/article-right-3.jpg');"></a>
	
	</div>
	
</div>






           
