<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Common\Module'                        => __DIR__ . '/Module.php',
    'Common\Controller\VisitController' => __DIR__ . '/src/Common/Controller/VisitController.php',
    'CommonTest\Framework\TestCase'        => __DIR__ . '/tests/Common/Framework/TestCase.php',
    'CommonTest\SampleTest'                => __DIR__ . '/tests/Common/SampleTest.php',
);
